gama-platform/gama

gama.core/src/gama/gaml/multi_criteria/MulticriteriaAnalyzeOperator.java, gama.core/tests/Spatial Tests/models/Relation.experiment, gama.library/models/Visualization and User Interaction/Visualization/3D Visualization/models/Quadratic Linear and Constant attenuation.gaml
This fixes the unit test model that doesn't pass and add a new model in the library to test the attenuation facets of a light
=> Improve library models

gama.core/src/gama/core/util/IList.java, gama.core/tests/Basic Tests/models/Lists.experiment, gama.library/models/GAML Syntax/Data Types And Structures/Lists.gaml
I will also add a unit test file based on Lists.gaml
=> Fixes #166

gama.core/src/gama/gaml/variables/Variable.java, gama.ui.shared/src/gama/ui/shared/parameters/AbstractEditor.java
This issue arose during the removal of the parameter facet. I've fixed it by reverting some of the code and giving the variables `parameter` and `category` default values in a variable.
But is it the proper place for those data to be stored now that parameters are only declared in statements ? Shouldn't we refactor a bit ? 
@AlexisDrogoul
=> Fixes #189

gama.core/src/gama/gaml/statements/TryStatement.java, gama.core/tests/Basic Tests/models/Lists.experiment
Also sets up the `#current_exception` accordingly in case it was not a `GamaRuntimeException`
=> Make the try statement catch all exception instead of just GamaRuntimeException

gama.core/src/gama/core/runtime/GAMA.java, gama.core/src/gama/core/runtime/concurrent/BufferingController.java, gama.ui.application/src/gama/ui/application/Application.java
attempt at flushing the (remaining) outputs when closing gama.
It works when killing the process from the task manager.
@AlexisDrogoul I forced the flush in the start and close function of the Application class, do you see any other location where it would make sense ?
=> Fix for #225

travis/zip_withjdk.sh
For some reason, Eclipse or JDK doesn't like to resolve JDK find at an upper level than the executable. Therefore, creating a symbolic link next to the GAMA bin pointing at the historical place of the JDK (ie. one level above) fixes this issue. Who knows... 
Fix #229
---
Tested on a Mac Mini M2 :heavy_check_mark:
=> [MACOS] Resolve embedded JDK with simlink

gama.core/src/gama/core/runtime/GAMA.java, gama.core/src/gama/core/runtime/concurrent/BufferingController.java, gama.core/src/gama/gaml/statements/SaveStatement.java, gama.headless/src/gama/headless/runtime/GamaHeadlessWebSocketServer.java
Provides a fix for repeated headers in case of file buffering and improves the documentation of the buffering code
=> Improves file buffering

gama.core/src/gama/core/outputs/layers/ImageLayer.java, gama.core/src/gama/gaml/operators/spatial/SpatialPunctal.java, gama.extension.image/src/gama/extension/image/GamaImage.java
fixes #262 but also some clues for further improvements.
@AlexisDrogoul could you double check this one as there are some points that I think could be improved in this class but I'm not sure yet:
1. This class uses a cached ImageProvider, but as the layer is only refreshed when the refresh facet is true, and that is checked in different parts of the code, I wonder what's the point of this object ? Maybe for files ? 
2. The BufferedImage to be drawn is actually generated in the `buildImage` method, but it is not returned, instead the ImageProvider that did generate it is returned and is then drawn with the `drawAsset` method. I think that this method is generating another bufferedimage but I'm not sure and it may depend on many factors (nature of the provider, facets of the layer/display …
=> Improvements for the image layer

gama.core/src/gama/gaml/operators/Strings.java
Takes a list of strings in parameter and produces the string resulting from their concatenation
=> Addition of concatenate operator

gama.headless/src/gama/headless/runtime/GamaHeadlessWebSocketServer.java
makes the main thread sleep during the infinite loop so the cpu can be used to do something else
=> Fixes #281

gama.ui.application/src/gama/ui/application/Application.java, gama.ui.application/src/gama/ui/application/workspace/WorkspacePreferences.java
When a workspace created with a previous version of GAMA is opened, the dialog now asks if the user wants to update it -- and we clear the old state if yes (prefs of plugins, etc.). It should cover 90% of the usages.
=> A better handling of old workspaces (fixes #224)

gama.core/src/gama/core/metamodel/population/GamaPopulation.java, gama.core/src/gama/core/metamodel/population/IPopulation.java, gama.core/src/gama/gaml/statements/RemoteSequence.java, gama.extension.serialize/src/gama/extension/serialize/binary/BinarySerialisation.java, gama.extension.serialize/src/gama/extension/serialize/binary/BinarySerialiser.java, gama.extension.serialize/src/gama/extension/serialize/binary/SimulationHistory.java, gama.extension.serialize/src/gama/extension/serialize/binary/SimulationSerialiser.java, gama.extension.serialize/src/gama/extension/serialize/gaml/CreateAgentsFromSerialisedFileDelegate.java
This commit should fix #246. The bytes composing the agent was compressed when saved but not decompressed.
=> Restores backward direction in experiments and saving/reading of agents in files

gama.annotations/src/gama/annotations/precompiler/GamlAnnotations.java, gama.core/src/gama/gaml/compilation/GamlAddition.java
Issue #260 should be fixed with this PR, as the examples are now correctly displayed in the editor hover popups
=> Displays the examples in the usages (popup doc, cf. #260)

gama.core/src/gama/core/kernel/batch/exploration/Exploration.java, gama.core/src/gama/core/kernel/batch/exploration/betadistribution/BetaExploration.java, gama.core/src/gama/core/kernel/batch/exploration/morris/MorrisExploration.java, gama.core/src/gama/core/kernel/batch/exploration/sobol/SobolExploration.java, gama.core/src/gama/core/kernel/batch/exploration/stochanalysis/StochanalysisExploration.java, gama.core/src/gama/core/kernel/batch/optimization/ALocalSearchAlgorithm.java, gama.core/src/gama/core/kernel/batch/optimization/HillClimbing.java, gama.core/src/gama/core/kernel/batch/optimization/Particle.java, gama.core/src/gama/core/kernel/batch/optimization/SimulatedAnnealing.java, gama.core/src/gama/core/kernel/batch/optimization/Swarm.java, gama.core/src/gama/core/kernel/batch/optimization/TabuSearch.java, gama.core/src/gama/core/kernel/batch/optimization/TabuSearchReactive.java, gama.core/src/gama/core/kernel/batch/optimization/genetic/GeneticAlgorithm.java, gama.core/src/gama/core/kernel/experiment/BatchAgent.java
In addition to addressing #320, I've taken the occasion to clean a little bit the call of the "run simulations" methods by the exploration algorithms.
=> Addresses #320: updates the status bar when simulations are run in parallel in batch

gama.core/src/gama/core/util/file/GamaGridFile.java
From now on (refer to #187  for context):
- write grid_data.contents will return a geometry (the enclosing envelope)
- write grid_data as matrix will return the matrix<float> of the values
- write grid_data as field will return the same values
=> Addresses #187 by correctly outputting a matrix from an asc file

gama.core/src/gama/core/outputs/layers/EventLayer.java, gama.core/src/gama/core/outputs/layers/IEventLayerListener.java, gama.core/src/gama/core/outputs/layers/KeyboardEventLayerDelegate.java, gama.ui.display.opengl/src/gama/ui/display/opengl/view/NEWTLayeredDisplayMultiListener.java, gama.ui.experiment/src/gama/ui/experiment/views/displays/SWTLayeredDisplayMultiListener.java
Adds common modifiers (shift, alt, ctrl and cmd) to the list of possible triggers for event layers to fix #257
=> Addresses #257

gama.core/src/gama/core/kernel/experiment/ExperimentAgent.java, gama.core/src/gama/core/kernel/experiment/ExperimentPlan.java, gama.core/src/gama/core/kernel/experiment/IExperimentPlan.java, gama.core/src/gama/core/outputs/AbstractOutputManager.java
Disposing the ExperimentAgent no longer automatically switches to the "Modeling" perspective: if the ExperimentPlan is marked as "reloading", we stay in the same perspective. @lesquoyb thanks to review this and merge it !
=> Patches the bug described in #334

gama.core/src/gama/core/kernel/batch/exploration/Exploration.java, gama.core/src/gama/core/kernel/batch/exploration/betadistribution/BetaExploration.java, gama.library/models/Model Exploration/Batch Simulation/Exploration.gaml
- Changes the type of `bootstrap` into int to fit its description and actual use
- Changes the model `Exploration.gaml` to use int factorial instead of a list to remove the warning
- fixes a typo in the documentation
=> [Exploration] Minor fixes in the facets of exploration methods

gama.extension.network/src/gama/extension/network/common/CompositeGamaMessage.java, gama.extension.network/src/gama/extension/network/common/Connector.java, gama.extension.serialize/models/Serialization/models/Create Simulation From File.gaml, gama.extension.serialize/src/gama/extension/serialize/binary/BinarySerialisation.java, gama.extension.serialize/src/gama/extension/serialize/binary/BinarySerialiser.java, gama.extension.serialize/src/gama/extension/serialize/binary/SimulationHistory.java, gama.extension.serialize/src/gama/extension/serialize/binary/SimulationSerialiser.java, gama.extension.serialize/src/gama/extension/serialize/gaml/SerialisationOperators.java, gama.extension.serialize/src/gama/extension/serialize/gaml/SimulationSaveDelegate.java, gama.extension.serialize/src/org/nustaq/serialization/FSTConfiguration.java, gama.ui.experiment/src/gama/ui/experiment/menus/SimulationsMenu.java
Simplifies lots of serialisation function. Fixes #351
=> Removes the option to zip or not the binary serialisation format

gama.headless/src/gama/headless/common/HeadLessErrors.java, gama.headless/src/gama/headless/runtime/HeadlessApplication.java, gama.headless/src/gama/headless/script/ExperimentationPlanFactory.java, gama.headless/src/gama/headless/xml/XMLWriter.java
Starting by fixing  #352: the problem happened when reaching the exportVariable function and trying to serialize the displays.
For now I'm just handling the case where the dataType variable is not defined. 
But the issue appeared on `Model 12.gaml` from the library of models, in which the displays are explicitly defined as 2d, so shouldn't dataType be DataType.DISPLAY2D when entering this function? And if so, what is the expected dataType in case of 3d display ?
@AlexisDrogoul any pointer ?
=> Miscellaneous fixes for headless legacy

gama.core/src/gama/core/kernel/batch/exploration/morris/MorrisExploration.java, gama.core/src/gama/core/kernel/batch/exploration/sampling/MorrisSampling.java
The sampling method for Morris was made out of a 'simplification' of the original matrix based formula. The new implementation is retro-engineered from SALib (MIT Licence) implementation.
=> Solves #367 by reimplementing morris sampling method following SALib implementation to avoid parameters getting out of bounds

gama.core/src/gama/core/outputs/InspectDisplayOutput.java, gama.ui.experiment/src/gama/ui/experiment/views/inspectors/PopulationInspectView.java
The issue was due to the browsing of agents from different species. The "common denominator" (i.e. `agent`) could not be found in the model. Problem is solved by moving to `SpeciesDescription` (rather than `ISpecies`) for traversing the species hierarchy.
=> Provides a fix for #379

gama.extension.network/src/gama/extension/network/tcp/ClientService.java
In case the socket was null (no call to connect or an exception when trying to), gama would raise a NPE when closing the simulation, which breaks the UI.
=> Fixes a potential NPE in network when closing an experiment

gama.core/src/gama/core/runtime/server/CommandExecutor.java, gama.core/src/gama/core/runtime/server/DefaultServerCommands.java, gama.core/src/gama/core/runtime/server/ISocketCommand.java
Add a "describe" gama server command to get a model description which gives :
- The species names and related actions
- The experiments and related parameters
=> Implementation of #402 +species informations

gama.core/src/gama/core/metamodel/population/GamaPopulation.java, gama.core/src/gama/gaml/operators/Maths.java, gama.library/models/Toy Models/Life/Life.gaml
- adds log operators for any base
- fixes wrong warning messages (addresses partly #398)
- makes the warnings non-blocking : log will return -Infinity in case of wrong operands as is default in java
=> Various improvements for the log operators

gaml.compiler/src/gaml/compiler/gaml/expression/GamlExpressionCompiler.java
I've removed the unescaping of string happening when transforming a StringLitteral into an expression because it seems like StringLitterals by definition are already escaped. This double unescaping leads in some edge cases to the "creation" special characters or trigger runtime exceptions, especially because the method was supporting escapings that were not allowed by gaml's syntax.
I've run all the unit tests, tried models that were using files, and a few examples that were causing troubles and everything seems alright. That being said, the change happening in the compiler, it could have unexpected repercussion so please test properly before merging
=> Fixes #467 and other bugs related to escaping/unescaping strings

gama.core/src/gama/core/runtime/server/DefaultServerCommands.java
- Avoid having several experiment running in background
- Probably related #610 
- and prevent some weird compilation exceptions
- Probably related #581
=> [GS GUI] Prevent loading new experiment if state is NOTREADY

gama.core/src/gama/core/kernel/experiment/DefaultExperimentController.java, gama.core/src/gama/core/kernel/root/PlatformAgent.java, gama.core/src/gama/core/runtime/GAMA.java, gama.headless/src/gama/headless/runtime/HeadlessApplication.java, gama.ui.application/src/gama/ui/application/Application.java
Application now calls GAMA.createGuiServer() at startup to avoid the lag mentioned in #631.
Fixes #631 if accepted.
=> Moves the server to GAMA directly (instead of PlatformAgent)
