gama-platform/gama

gama.core/tests/Basic Tests/models/Lists.experiment
gama.library/models/Toy Models/Epidemiology/models/SIR with FSM Architecture.gaml

Improve models from library

---

.github/workflows/trigger-doc-regeneration.yaml

Fix documentation generation workflow

---

gama.core/tests/Basic Tests/models/Lists.experiment

- force rng
- removes warnings
- uncomment random operators

Improves lists.experiment

---

gama.core/src/gama/core/util/GamaDate.java
gama.core/src/gama/gaml/operators/Dates.java

Test model:
```
model EveryTest
global {
float step <- 1 #mn;
float t1;
float t2;
int nb_pas_ok <- 0;
reflex testEvery {
float t <- gama.machine_time;
bool e <- every(1 #mn, false);
t1 <- t1 + gama.machine_time - t;
t <- gama.machine_time;
bool e2 <- every(1 #h);
t2 <- t2 + gama.machine_time - t;
if (e != e2) {
nb_pas_ok <- nb_pas_ok +1;
}
if (cycle mod 1000) = 0 {
write "t normal: " + t1 + " t optimized:" + t2 + " nb_pas_ok: " + nb_pas_ok;
}
}	
}
experiment EveryTest type: gui ;
```

adresses issue #271 - optimized "every"

---

.github/workflows/travis-publish-github.yaml

Enable "generate release note" - Fix #249

---

gama.core/src/gama/core/runtime/concurrent/BufferingController.java

Fixes ConcurrentModificationException in batch experiments using buffering strategies
- adds synchronized modifier to functions using the map in BufferingController
- adds static modifier to functions that needed it

Fixes 288 

---

gama.extension.image/models/Images/models/Image Manipulation.gaml
gama.extension.image/src/gama/extension/image/ImageOperators.java

The Image Manipulation models has also been adapted to use it.

Fix for #176 by adding a % for brightening images

---

gama.core/src/gama/gaml/statements/BenchmarkStatement.java

- Adds end, color and buffering facets to match with the write statement
- also adds a linebreak at the end of the message by default
- go through the BufferingController instead of writing directly in the console

General improvements of the benchmark statement

---

gama.core/src/gama/core/kernel/batch/exploration/Exploration.java
gama.core/src/gama/core/kernel/experiment/ExperimentAgent.java
gama.core/src/gama/gaml/statements/LoopStatement.java
gama.core/src/gama/gaml/statements/PutStatement.java
gama.headless/src/gama/headless/runtime/HeadlessApplication.java
gama.ui.application/src/gama/ui/application/Application.java

When in headless batch, add a controller to the list of controllers in `GAMA.java` to stop the error propagation

Fixes #301 + some documentation

---

gama.core/src/gama/core/kernel/batch/exploration/AExplorationAlgorithm.java

Add some safeguards to prevent infinite looping in AExplorationAlgorithm

---

gama.core/src/gama/core/common/interfaces/GeneralSynchronizer.java
gama.core/src/gama/core/common/interfaces/IDisplaySurface.java
gama.core/src/gama/core/kernel/experiment/AbstractExperimentController.java
gama.core/src/gama/core/kernel/experiment/DefaultExperimentController.java
gama.core/src/gama/core/kernel/simulation/SimulationAgent.java
gama.core/src/gama/core/outputs/AbstractOutputManager.java
gama.core/src/gama/core/outputs/IOutputManager.java
gama.core/src/gama/core/outputs/display/NullDisplaySurface.java
gama.core/src/gama/core/runtime/concurrent/SimulationRunner.java
gama.extension.image/src/gama/extension/image/ImageDisplaySurface.java
gama.extension.physics/src/gama/extension/physics/native_version/NativeBulletPhysicalWorld.java
gama.headless/src/gama/headless/server/GamaServerExperimentController.java
gama.library/models/Toy Models/Ants (Foraging and Sorting)/models/Ant Foraging.gaml
gama.library/models/Toy Models/Ants (Foraging and Sorting)/models/Ant Sorting.gaml
gama.library/models/Toy Models/Traffic/models/Traffic and Pollution.gaml
gama.ui.display.java2d/src/gama/ui/display/java2d/Java2DDisplaySurface.java
gama.ui.display.opengl/src/gama/ui/display/opengl/renderer/JOGLRenderer.java
gama.ui.display.opengl/src/gama/ui/display/opengl/view/SWTOpenGLDisplaySurface.java
gama.ui.experiment/src/gama/ui/experiment/menus/OutputsMenu.java
gama.ui.experiment/src/gama/ui/experiment/views/displays/LayeredDisplayView.java

First commit fixes #341 and https://groups.google.com/g/gama-platform/c/9YAJXb2HR8M/m/w6S5NMKSBAAJ
More to come.

Displays+Monitors syncing issues (#341 + #339)

---

gama.ui.experiment/src/gama/ui/experiment/views/console/ConsoleView.java
gama.ui.shared/src/gama/ui/shared/resources/GamaColors.java

Provides a lighter color for the text in the console when in dark mode. Allows to adjust the level of brightness when computing lighter colors.

Fixes the color of text in a dark console

---

gama.core/src/gama/gaml/statements/test/TestStatement.java

Fix #425 by shortening test names

---

gama.core/src/gama/gaml/operators/Comparison.java

This PR is supposed to fix #424

Add the missing operator computing the difference between two integers

---

gama.core/src/gama/core/common/preferences/GamaPreferences.java
gama.ui.editor/src/gaml/compiler/ui/editor/GamlEditor.java

Fixes #391 : Add a preference to surround highlighted text and the mechanism in GAML Editor

---

gama.core/src/gama/core/kernel/root/PlatformAgent.java
gama.core/src/gama/core/runtime/GAMA.java
gama.core/src/gama/core/runtime/server/CommandExecutor.java
gama.core/src/gama/core/runtime/server/CommandResponse.java
gama.core/src/gama/core/runtime/server/DefaultServerCommands.java
gama.core/src/gama/core/runtime/server/GamaGuiWebSocketServer.java
gama.core/src/gama/core/runtime/server/GamaServerConsoleListener.java
gama.core/src/gama/core/runtime/server/GamaServerMessage.java
gama.core/src/gama/core/runtime/server/GamaServerMessager.java
gama.core/src/gama/core/runtime/server/GamaServerStatusDisplayer.java
gama.core/src/gama/core/runtime/server/GamaWebSocketServer.java
gama.core/src/gama/core/runtime/server/IGamaServer.java
gama.core/src/gama/core/runtime/server/ISocketCommand.java
gama.core/src/gama/core/runtime/server/MessageType.java
gama.core/src/gama/core/runtime/server/ReceivedMessage.java
gama.core/src/gama/core/util/file/json/Json.java
gama.extension.image/src/gama/extension/image/ImageOperators.java
gama.headless/src/gama/headless/listener/LoadCommand.java
gama.headless/src/gama/headless/listener/PlayCommand.java
gama.headless/src/gama/headless/listener/StopCommand.java
gama.headless/src/gama/headless/runtime/GamaHeadlessWebSocketServer.java
gama.headless/src/gama/headless/runtime/HeadlessApplication.java
gama.headless/src/gama/headless/server/GamaServerExperimentController.java
gama.headless/src/gama/headless/server/GamaServerGUIHandler.java

Basic infrastructure of listeners in the GamaWebSocketServer. Will fix #438

Additions of listeners to GAMA server command processing 

---

gama.core/src/gama/gaml/descriptions/IDescription.java
gama.core/src/gama/gaml/descriptions/StatementDescription.java
gama.core/src/gama/gaml/descriptions/SymbolDescription.java

Fixes #447 by taking into account the call of actions without arguments (and without defaults for the parameters)

Fixes #447: flags invocations of actions w/o any arguments (and no defaults)

---

gama.core/src/gama/gaml/statements/draw/BandsBasedMeshColorProvider.java
gama.core/src/gama/gaml/statements/draw/MeshDrawingAttributes.java

A quick fix to render field as RGB based on bands

[FIELD] Bugfix #460 - remove the skip of first band to render RGB from field bands

---

gama.core/src/gama/core/util/path/GamaPath.java
gama.core/src/gama/gaml/operators/Files.java

- also translate some comments

[gaml] Adds the to_absolute_file operator

---

gama.extension.network/models/Network/1 Get started/1 Simple ping-pong.gaml
gama.extension.network/models/Network/1 Get started/2 Broadcast to all.gaml
gama.extension.network/models/Network/1 Get started/3 Broadcast to group.gaml
gama.extension.network/models/Network/2 Available protocols/HTTP Request/HTTP POST.gaml
gama.extension.network/models/Network/2 Available protocols/MQTT protocol/Example_MQTT_Receive.gaml
gama.extension.network/models/Network/2 Available protocols/MQTT protocol/Example_MQTT_Receive_Agent.gaml
gama.extension.network/models/Network/2 Available protocols/MQTT protocol/Example_MQTT_Send.gaml
gama.extension.network/models/Network/2 Available protocols/MQTT protocol/Example_MQTT_Send_Agent.gaml
gama.extension.network/models/Network/2 Available protocols/TCP protocol/TCP Server Example.gaml
gama.extension.network/models/Network/2 Available protocols/WebSocket protocol/WebSocket Server Example.gaml
gama.extension.network/models/Network/3 Advanced features/1 Pong Teleportation (send agent).gaml
gama.extension.network/models/Network/3 Advanced features/2 External GAMA controller.gaml
gama.extension.network/src/gama/extension/network/httprequest/HTTPRequestConnector.java
gama.extension.network/src/gama/extension/network/mqtt/MQTTConnector.java
gama.extension.network/src/gama/extension/network/skills/INetworkSkill.java
gama.extension.network/src/gama/extension/network/skills/NetworkSkill.java
gama.extension.network/src/gama/extension/network/tcp/TCPConnector.java
gama.extension.network/src/gama/extension/network/websocket/WebSocketConnector.java
gama.extension.pedestrian/models/Pedestrian Skill/models/Complex environment - walk.gaml

- adds disconnect action to  #446
- code cleanup
- better handling of network errors for #433

[network] various improvements for network skill

---

gama.core/src/gama/core/util/graph/PathComputer.java

Optimization for large dynamic graphs

In incVersion/setVersion, replace release by new - added volatile

---

gama.product/extraresources/installer/unix/DEBIAN/control
travis/bumpGamaVersion.sh

Fix issue 605

---

gama.core/src/gama/core/runtime/server/DefaultServerCommands.java

[GS] explicitly parse values into json before sending them back in expression command

---

gama.core/src/gama/core/common/interfaces/IGui.java
gama.core/src/gama/core/common/util/FileUtils.java
gama.core/src/gama/core/util/file/GamaCSVFile.java
gama.core/src/gama/core/util/file/GamaFileMetaData.java
gama.core/src/gama/core/util/file/GamaOsmFile.java
gama.core/src/gama/core/util/file/GamaShapeFile.java
gama.core/src/gama/core/util/file/GamlFileInfo.java
gama.core/src/gama/core/util/file/IGamaFileMetaData.java
gama.core/src/gama/gaml/compilation/GamlIdiomsProvider.java
gama.core/src/gama/gaml/interfaces/IGamlDescription.java
gama.ui.editor/src/gaml/compiler/ui/editor/GamlHyperlinkDetector.java
gama.ui.editor/src/gaml/compiler/ui/hover/GamlHoverDocumentationProvider.java
gama.ui.editor/src/gaml/compiler/ui/quickfix/GamlQuickfixProvider.java
gama.ui.navigator/src/gama/ui/navigator/metadata/FileMetaDataProvider.java
gama.ui.navigator/src/gama/ui/navigator/metadata/ImageInfo.java
gama.ui.shared/src/gama/ui/shared/access/GamlAccessContents2.java
gama.ui.shared/src/gama/ui/shared/utils/FileOpener.java
gama.ui.shared/src/gama/ui/shared/utils/SwtGui.java
gaml.compiler/src/gaml/compiler/gaml/resource/GamlResourceInfoProvider.java

Related to #599 and hopefully fixing it. Please review it and merge it if it is ok -- note that one issue might be that the first execution of this results in an error and force the user to refresh files metadata in the navigator, as the metadata of files needs to be slightly changed before being used this way.

Adds the possibility to browse files in the global search

---

gama.ui.editor/src/gaml/compiler/ui/editor/GamlEditor.java
gama.ui.shared/src/gama/ui/shared/controls/FlatButton.java
gama.ui.shared/src/gama/ui/shared/views/toolbar/GamaCommand.java
gama.ui.shared/src/gama/ui/shared/views/toolbar/GamaToolbar2.java

Different tries to understand what is happening at 150% on Windows only... Seems that buttons with an odd width are not displayed, while buttons with an even width are... go figure.

Fixes disappearing icons on Windows

---

gama.core/src/gama/core/metamodel/agent/AbstractAgent.java

- adds an automatic line break at the end
- adds parameters to let the users set separator and ending string

[gaml] improves the 'debug' action of agents
